#!/usr/bin/env bash
# Noticeboard kiosk — auto-generated by installer. See what it did: journalctl -t noticeboard-kiosk
# The Noticeboard folder: this script is its start-kiosk.sh
DIR=$(cd "$(dirname "$0")" && pwd)
# The Server's own address, on the port in its settings (read the way the server reads it; 3000
# if that fails). Read again whenever the browser starts, so a new port is followed.
server_url() {
  local port=""
  port=$(cd "$DIR" 2>/dev/null && node -e "require('./server/utils/configIO').readConfig('data/config.json')
    .then((c) => console.log(c.port || 3000), () => console.log(3000))" 2>/dev/null) || true
  [[ "$port" =~ ^[0-9]+$ ]] || port=3000
  echo "http://localhost:$port/"
}
URL=$(server_url)
# The kiosk browser has a profile of its own, so a browser opened from the desktop (e.g. for
# the admin panel) is an ordinary window, never part of the full-screen kiosk
PROFILE="$HOME/.config/noticeboard-kiosk"
log() { logger -t noticeboard-kiosk "$*" 2>/dev/null || true; }

# Newer Raspberry Pi OS calls the browser chromium; older releases chromium-browser
BROWSER=$(command -v chromium-browser || command -v chromium || true)
if [ -z "$BROWSER" ]; then
  log "Chromium isn't installed; run the Noticeboard installer again"
  exit 1
fi
FLAGS=(--noerrdialogs --disable-infobars --disable-session-crashed-bubble
       --disable-component-update --check-for-update-interval=31536000
       --no-first-run --no-default-browser-check --disable-search-engine-choice-screen
       --password-store=basic --user-data-dir="$PROFILE"
       --autoplay-policy=no-user-gesture-required)   # background audio plays without a click

# Opening the browser before the server answers would leave it on an error page
wait_for_server() {
  URL=$(server_url)
  log "Waiting for the Server at $URL"
  until curl -sf "$URL" >/dev/null 2>&1; do
    sleep 2
  done
}
wait_for_server

# Disable display blanking and power management (X11 desktops; ignored under Wayland)
xset s off    2>/dev/null || true
xset -dpms    2>/dev/null || true
xset s noblank 2>/dev/null || true

# The exit button in the viewer's top-right corner asks the server; the answer is for this
# device only, so other screens are never affected
exit_requested() {
  [ "$(curl -s -X POST --max-time 3 "${URL}api/device/kiosk-exit/claim" 2>/dev/null)" = '{"exit":true}' ]
}

# Close the full-screen browser, open the viewer in an ordinary window of the desktop's own
# browser, and stop. This screen goes back to kiosk mode the next time it starts up.
leave_kiosk() {
  log "Leaving kiosk mode, as asked on this screen; opening a normal browser window"
  kill "$1" 2>/dev/null
  wait "$1" 2>/dev/null
  sleep 1
  nohup "$BROWSER" --no-first-run "${URL}?kiosk=off" >/dev/null 2>&1 &
  exit 0
}

# Keep the browser running: if it ever exits or crashes, start it again. To leave the kiosk,
# use the exit button in the viewer's top-right corner (move the mouse to show it).
while true; do
  log "Starting $BROWSER"
  "$BROWSER" "${FLAGS[@]}" --kiosk "$URL" &
  pid=$!
  while kill -0 "$pid" 2>/dev/null; do
    sleep 3
    if exit_requested; then
      leave_kiosk "$pid"
    fi
  done
  wait "$pid"
  log "Browser exited (code $?); starting it again"
  sleep 5
  wait_for_server
done
