#!/usr/bin/env bash
# Noticeboard Client kiosk — auto-generated by installer. See what it did: journalctl -t noticeboard-kiosk
SERVER_URL=""
MACS_HTML=""
PAGE=/tmp/noticeboard-waiting.html
# The waiting page runs in its own browser profile, so it can't hand over to the real one
WAITING_PROFILE=/tmp/noticeboard-waiting-profile
# So does the kiosk itself, so a browser opened from the desktop is an ordinary window
KIOSK_PROFILE="$HOME/.config/noticeboard-kiosk"
log() { logger -t noticeboard-kiosk "$*" 2>/dev/null || true; }

# Newer Raspberry Pi OS calls the browser chromium; older releases chromium-browser
BROWSER=$(command -v chromium-browser || command -v chromium || true)
if [ -z "$BROWSER" ]; then
  log "Chromium isn't installed; run the Noticeboard installer again"
  exit 1
fi
FLAGS=(--noerrdialogs --disable-infobars --disable-session-crashed-bubble
       --disable-component-update --check-for-update-interval=31536000
       --no-first-run --no-default-browser-check --disable-search-engine-choice-screen
       --password-store=basic
       --autoplay-policy=no-user-gesture-required)   # background audio plays without a click

# Disable display blanking
xset s off    2>/dev/null || true
xset -dpms    2>/dev/null || true
xset s noblank 2>/dev/null || true

# The local page shown until the Server answers: this Client's MAC address and why it's waiting.
# It reloads itself every 10 s, so rewriting the file changes what's on screen.
write_page() {   # write_page <heading> <note>
  cat > "$PAGE" <<HTML
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="refresh" content="10">
  <title>Noticeboard Client</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #0f172a; color: #e2e8f0;
      font-family: monospace;
      display: flex; align-items: center; justify-content: center;
      min-height: 100vh;
    }
    .box { text-align: center; padding: 2rem; }
    .heading { color: #94a3b8; font-size: 1rem; margin-bottom: 2rem; }
    table { margin: 0 auto; border-collapse: collapse; }
    .iface { color: #64748b; font-size: 0.85rem; padding: 4px 20px 4px 0; text-align: right; }
    .mac   { font-size: 1.6rem; letter-spacing: 0.08em; padding: 4px 0; }
    .note  { color: #475569; font-size: 0.8rem; margin-top: 2rem; line-height: 1.5; }
  </style>
</head>
<body>
  <div class="box">
    <p class="heading">$1</p>
    <table>$MACS_HTML</table>
    <p class="note">$2</p>
  </div>
</body>
</html>
HTML
}

WAITING_PID=""
stop_waiting_page() {
  if [ -n "$WAITING_PID" ]; then
    kill "$WAITING_PID" 2>/dev/null
    wait "$WAITING_PID" 2>/dev/null
    WAITING_PID=""
    sleep 2
  fi
}

# Show the noticeboard as soon as the Server answers, and until then the local page, checking
# every 10 s. Nobody needs to restart this display: not while it waits for approval, not while
# the Server is down or restarting, and not if the browser exits or crashes.
while true; do
  STATE=""
  while true; do
    HTTP_CODE=$(curl -o /dev/null -s -w "%{http_code}" --max-time 10 "$SERVER_URL" 2>/dev/null || echo "000")
    [ "$HTTP_CODE" = "200" ] && break
    if [ "$HTTP_CODE" = "404" ]; then NEW=approval; else NEW=server; fi
    if [ "$NEW" != "$STATE" ]; then
      STATE=$NEW
      if [ "$STATE" = approval ]; then
        write_page "This Client is waiting for MAC address approval" \
          "Give the MAC address above to your Noticeboard admin.<br>The noticeboard appears by itself once this Client is approved."
      else
        write_page "Waiting for the Noticeboard Server at $SERVER_URL" \
          "Checking every 10 seconds.<br>The noticeboard appears by itself as soon as the Server answers."
      fi
      log "Server answered HTTP $HTTP_CODE (000 = unreachable); showing the waiting page ($STATE)"
    fi
    if [ -z "$WAITING_PID" ] || ! kill -0 "$WAITING_PID" 2>/dev/null; then
      "$BROWSER" "${FLAGS[@]}" --user-data-dir="$WAITING_PROFILE" --kiosk "file://$PAGE" &
      WAITING_PID=$!
    fi
    sleep 10
  done
  stop_waiting_page
  log "Server $SERVER_URL answered; starting $BROWSER"
  "$BROWSER" "${FLAGS[@]}" --user-data-dir="$KIOSK_PROFILE" --kiosk "$SERVER_URL" &
  pid=$!
  # The exit button in the viewer's top-right corner asks the Server; the answer is for this
  # device only. Then: an ordinary browser window, and no more kiosk until the next start-up.
  while kill -0 "$pid" 2>/dev/null; do
    sleep 3
    if [ "$(curl -s -X POST --max-time 3 "$SERVER_URL/api/device/kiosk-exit/claim" 2>/dev/null)" = '{"exit":true}' ]; then
      log "Leaving kiosk mode, as asked on this screen; opening a normal browser window"
      kill "$pid" 2>/dev/null
      wait "$pid" 2>/dev/null
      sleep 1
      nohup "$BROWSER" --no-first-run "$SERVER_URL/?kiosk=off" >/dev/null 2>&1 &
      exit 0
    fi
  done
  wait "$pid"
  log "Browser exited (code $?); starting it again"
  sleep 5
done
