#!/usr/bin/env bash
# installer-remote-client.sh
# Sets up a Raspberry Pi as a remote display that connects to an existing Noticeboard server.
# Run with: sudo bash installer-remote-client.sh
set -euo pipefail

KIOSK_SCRIPT="/usr/local/bin/noticeboard-kiosk.sh"
AUTOSTART_FILE="/etc/xdg/autostart/noticeboard-kiosk.desktop"

# ── Root check ────────────────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  echo "ERROR: Run this script with sudo."
  exit 1
fi

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║    Noticeboard — remote display installer    ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ── Prompt for server URL ─────────────────────────────────────────────────────
read -rp "Noticeboard server URL (e.g. http://192.168.1.10:3000): " SERVER_URL
SERVER_URL="${SERVER_URL%/}"   # strip trailing slash

if [ -z "$SERVER_URL" ]; then
  echo "ERROR: Server URL is required."
  exit 1
fi

echo ""
echo "Server URL: $SERVER_URL"
echo ""

# ── System packages ───────────────────────────────────────────────────────────
echo "▸ Installing packages..."
apt-get update -qq
apt-get install -y -qq chromium-browser curl
apt-get install -y -qq unclutter 2>/dev/null || true

# ── Kiosk wrapper script ──────────────────────────────────────────────────────
echo "▸ Installing kiosk script..."

# Collect this Pi's MAC addresses for the approval page
MACS_HTML=""
for iface_path in /sys/class/net/*/; do
  iface=$(basename "$iface_path")
  [ "$iface" = "lo" ] && continue
  mac=$(cat "$iface_path/address" 2>/dev/null || true)
  [ -z "$mac" ] || [ "$mac" = "00:00:00:00:00:00" ] && continue
  MACS_HTML="${MACS_HTML}<tr><td class='iface'>${iface}</td><td class='mac'>${mac}</td></tr>"
done

cat > "$KIOSK_SCRIPT" <<KIOSK
#!/usr/bin/env bash
# Noticeboard remote display kiosk — auto-generated by installer
SERVER_URL="${SERVER_URL}"

# Disable display blanking
xset s off    2>/dev/null || true
xset -dpms    2>/dev/null || true
xset s noblank 2>/dev/null || true
command -v unclutter >/dev/null 2>&1 && unclutter -idle 1 -root &

# Check whether this device is approved by the server
HTTP_CODE=\$(curl -o /dev/null -s -w "%{http_code}" --max-time 10 "\${SERVER_URL}" 2>/dev/null || echo "000")

if [ "\$HTTP_CODE" = "200" ]; then
  # Approved — launch display directly
  exec chromium-browser \\
    --noerrdialogs --disable-infobars --disable-session-crashed-bubble \\
    --disable-component-update --check-for-update-interval=31536000 \\
    --kiosk "\${SERVER_URL}"
fi

# Not yet approved — show a page with this device's MAC address.
# JavaScript in the page polls the server and redirects once approved.
TMPFILE=\$(mktemp /tmp/nb-pending.XXXXXX.html)
cat > "\$TMPFILE" <<'HTML'
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Waiting for approval</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #0f172a; color: #e2e8f0;
      font-family: monospace;
      display: flex; align-items: center; justify-content: center;
      min-height: 100vh;
    }
    .box { text-align: center; padding: 2rem; }
    .heading { color: #94a3b8; font-size: 1rem; margin-bottom: 2rem; }
    table { margin: 0 auto; border-collapse: collapse; }
    .iface { color: #64748b; font-size: 0.85rem; padding: 4px 20px 4px 0; text-align: right; }
    .mac   { font-size: 1.6rem; letter-spacing: 0.08em; padding: 4px 0; }
    .note  { color: #475569; font-size: 0.8rem; margin-top: 2rem; line-height: 1.5; }
  </style>
  <script>
    var SERVER = "NOTICEBOARD_SERVER_URL_PLACEHOLDER";
    function poll() {
      fetch(SERVER, { method: "HEAD" })
        .then(function(r) {
          if (r.ok) { window.location.href = SERVER; }
          else { setTimeout(poll, 5000); }
        })
        .catch(function() { setTimeout(poll, 5000); });
    }
    setTimeout(poll, 5000);
  </script>
</head>
<body>
  <div class="box">
    <p class="heading">This display is waiting for MAC address approval</p>
    <table>
      MACS_PLACEHOLDER
    </table>
    <p class="note">
      Give the MAC address above to your Noticeboard admin.<br>
      This page will redirect automatically once approved.
    </p>
  </div>
</body>
</html>
HTML

# Substitute placeholders
sed -i "s|NOTICEBOARD_SERVER_URL_PLACEHOLDER|\${SERVER_URL}|g" "\$TMPFILE"
sed -i "s|MACS_PLACEHOLDER|${MACS_HTML}|g" "\$TMPFILE"

exec chromium-browser \\
  --noerrdialogs --disable-infobars --disable-session-crashed-bubble \\
  --disable-component-update --check-for-update-interval=31536000 \\
  --kiosk "file://\${TMPFILE}"
KIOSK

chmod +x "$KIOSK_SCRIPT"

# ── XDG autostart ─────────────────────────────────────────────────────────────
echo "▸ Installing autostart entry..."
cat > "$AUTOSTART_FILE" <<DESK
[Desktop Entry]
Name=Noticeboard Kiosk
Exec=$KIOSK_SCRIPT
Type=Application
X-GNOME-Autostart-enabled=true
DESK

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║            Installation complete             ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  This Pi will display: $SERVER_URL"
echo ""
echo "  If MAC filtering is enabled on the server, the display will"
echo "  show this device's MAC address until the admin approves it."
echo ""
echo "Reboot to start the kiosk automatically."
echo ""
